<?php

namespace App\Exceptions;

use App\AppHelper\AppHelper;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        if ($request->wantsJson()) {
            if ($e instanceof AuthenticationException) {
                return AppHelper::logErrorException($e, 401);
            } else {
                return AppHelper::logErrorException($e, 200);
            }
        } else {
            return parent::render($request, $e); // TODO: Change the autogenerated stub
        }
    }

}
